### ISSUE TITLE
Temperature & max_tokens

### ISSUE THREAD

**Issue by anastasiuspernat** [kijai/ComfyUI-LLaVA-OneVision#1]
Awesome extension! Exactly what I was looking for. Deserves more stars!

One thing I noticed that there's no slider for temperature, the official public HF space is using value 0.6, and from my tests it generates a more detailed output. Also max tokens can be 8192 - adds more details too. Thank you!

**Comment by kijai** [comment]
Thanks! And yeah you're right, should expose those, done all that now!
